### PR TITLE
build: rollup

### PR DESCRIPTION
**Pull request by zhuangya**
ref #12

### CODE REVIEW

**Comment by zhuangya** [comment]
maybe there is still some problems, but here is the built file size delta:

before(with webpack):

`-rw-r--r--  1 nos  staff   10074  6 14 16:16 index.js`

after(with rollup):

`-rw-r--r--  1 nos  staff   3909  6 14 16:16 index.js`

**Comment by sarneeh** [comment]
Wow! Nice! Thank you! 💃 

Btw. I've re-pushed your branch to trigger the CI build as I've messed up the configuration out there, sorry 😄

**Comment by zhuangya** [comment]
just a suggestion:

maybe have a try of [microbundle](https://github.com/developit/microbundle)?

**Comment by sarneeh** [comment]
Thanks for the suggestion! I'll check it out :) I'm just not sitting on this right now because I have no time 😢

**Comment by sarneeh** [comment]
I'll come back to this when I'll have more time. Closing for now.

**Comment by AndyOGo** [comment]
This would be awesome

**Comment by sarneeh** [comment]
I declined this PR because I wanted to switch to rollup completely in this project - so the library itself and the example showcase. This PR only changes the lib. Also I had some problems with the build. Unfortunately didn't have time to investigate more 😭

**Comment by AndyOGo** [comment]
I understand.

Well I love webpack and rollup and parcel, you name.
I can provide a PR if you don't mind.

**Comment by AndyOGo** [comment]
@sarneeh 
So I created a PR https://github.com/sarneeh/reaptcha/pull/196

IMHO library builds are best done with just a bundler like rollup (without the loader overhead).
For the website, I would stick to bundler+loader like webpack or parcel.
May lets continue discussion within the other PR.

**Pull request closed without merging**
