### PR TITLE
Fix React 18 throw error issue

### PR DESCRIPTION
**Pull request by Cow258**

### CODE REVIEW

**Comment by jsardev** [comment]
@Cow258 Hey! Thanks for the PR!

I'm wondering... why did you remove the workflows? 😅

**Comment by jsardev** [comment]
Closing due to no response.

**Comment by Cow258** [comment]
> @Cow258 Hey! Thanks for the PR!
> 
> I'm wondering... why did you remove the workflows? 😅

Hi @sarneeh,

I apologize for any inconvenience caused by my previous actions. I would like to respectfully inform you that after attempting to contribute via a pull request, I discovered that my method was not sufficient in solving the problem at hand. In order to test my code on certain environments that required installation from npm, I made some changes and force pushed and published to npm. However, I neglected to remove the pull request.

I sincerely apologize for any confusion or disruption this may have caused. Please note that my final solution involved using CloudFlare Turnstile.

Thank you for your understanding and patience.

**Comment by jsardev** [comment]
@Cow258 No problem 👍

**Pull request closed without merging**
