### PR TITLE
docs: project readme as npm readme

### LINKED ISSUE #110: reaptcha links and readme on npmjs.com
The reaptcha presence at npmjs.com looks a little bit barren to me. There is no link to the github repo and no working Readme.

This initially raised some flags when I was looking for a suitable reCAPTCHA package, so you might want to consider to add some details to https://www.npmjs.com/package/reaptcha

### PR DESCRIPTION
**Pull request by zhuangya**
close #110

### CODE REVIEW

**Comment by zhuangya** [comment]
i moved project's readme into `lib/` and set a symbolic link of it,

does it make sense to you? @sarneeh

**Comment by sarneeh** [comment]
Will GitHub resolve the symlink on the root directory? If yes, I'm ok with this PR 😄 One request tho: please remove the `yarn.lock` change 😄

**Comment by zhuangya** [comment]
> Will GitHub resolve the symlink on the root directory?

sure, GitHub will resolve the symlink, you can check it out on my forked page:

https://github.com/zhuangya/reaptcha

also, `yarn.lock` has already been removed.

**Comment by sarneeh** [comment]
@zhuangya Awesome! But... I meant removing the `changes` from `yarn.lock`, not deleting the whole file 😄

**Comment by sarneeh** [comment]
@zhuangya Thank you for contributing! 😄

**Comment by zhuangya** [comment]
great!

**Pull request merged**
