### PR TITLE
Add TypeScript definition file

### PR DESCRIPTION
**Pull request by ksocha**
I've created TS definition file for this package in my project so I may as well share it.

### CODE REVIEW

**Comment by sarneeh** [comment]
Awesome! Thank you :smile:

**Comment by sarneeh** [comment]
Released in `1.5.1`.

**Comment by ksocha** [comment]
It would be good to add the info to the changelog and let people know what was added.

**Comment by sarneeh** [comment]
Uh, this is auto-generated from commits. Dunno why it didn't stop you from creating a commit which does not follow the conventional commits guideline :thinking:

**Comment by sarneeh** [comment]
https://github.com/sarneeh/reaptcha/commit/d708e478a15a5450250fe0dd1c587bdb572b8873

**Pull request merged**
